openapi: 3.0.0
info:
  title: Flight Check-In Step 7
  version: '1.0'
servers:
  - url: 'http://localhost:4010'
paths:
  /check-in:
    post:
      summary: ''
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/passenger.v1.yaml
      parameters:
        - schema:
            type: string
            pattern: '^[A-Z]{2} [1-9]{4}$'
          in: query
          name: flightNumber
      security:
        - API Key: []
    put:
      summary: ''
      operationId: put-check-in
      responses:
        '200':
          description: OK
      security:
        - API Key: []
  /check-in/passengers: {}
components:
  securitySchemes:
    API Key:
      name: x-api-key
      type: apiKey
      in: header
